### PR TITLE
Removed extra parameters from variadic functions' prototype in spuro.h

### LINKED ISSUE #3: [BUG] Zero-arg variadic macro warning leads to build failure on clang
Using clang, build fails with the following error:

`error: token pasting of ',' and __VA_ARGS__ is a GNU extension [-Werror,-Wgnu-zero-variadic-macro-arguments]`

### PR DESCRIPTION
**Pull request by ghost**
Removed extra arguments from functions' prototypes declared in header file to fix #3 

> [!TIP]
> Please add clang compiler test in workflow

### CODE REVIEW

**Comment by jgabaut** [comment]
I am confused.

Why did you open a new PR, closed the old one, and never replied to my questions? From my pov, I'm still waiting on them replies.

**Comment by ghost** [comment]
> I am confused.
> 
> Why did you open a new PR, closed the old one, and never replied to my questions? From my pov, I'm still waiting on them replies.

I knew it .. i was wondering why you didn't review it and you forgot to publish your review.
None of your questions were visible to me.

Reason for discarding old PR is because i submitted one more commit which was breaking.
I will be adding new changes in a PR fashion from now on-wards so that i can revert them easily.

File: src/spuro.h [hunk 1]
```diff
@@ -153,24 +153,24 @@ void spr_logf_(const Spuro spr, SpuroLevel level, SpuroColor color, SpuroLoc loc
...
 
-#define spr_logf(spr, format, ...) spr_logf_((spr), SPR_NOLVL, SPR_COLOR_AUTO, SPR_HERE, false, false, (format), ## __VA_ARGS__)
-#define spr_tlogf(spr, format, ...) spr_logf_((spr), SPR_NOLVL, SPR_COLOR_AUTO, SPR_HERE, false, true, (format), ## __VA_ARGS__)
-#define spr_clogf(spr, color, format, ...) spr_logf_((spr), SPR_NOLVL, (color), SPR_HERE, false, false, (format), ## __VA_ARGS__)
-#define spr_tclogf(spr, color, format, ...) spr_logf_((spr), SPR_NOLVL, (color), SPR_HERE, false, true, (format), ## __VA_ARGS__)
-#define spr_logf_to(spr, level, format, ...) spr_logf_((spr), (level), SPR_COLOR_AUTO, SPR_HERE, false, false, (format), ## __VA_ARGS__)
-#define spr_tlogf_to(spr, level, format, ...) spr_logf_((spr), (level), SPR_COLOR_AUTO, SPR_HERE, false, true, (format), ## __VA_ARGS__)
-#define spr_clogf_to(spr, color, level, format, ...) spr_logf_((spr), (level), (color), SPR_HERE, false, false, (format), ## __VA_ARGS__)
-#define spr_tclogf_to(spr, color, level, format, ...) spr_logf_((spr), (level), (color), SPR_HERE, false, true, (format), ## __VA_ARGS__)
+#define spr_logf(spr, ...) spr_logf_((spr), SPR_NOLVL, SPR_COLOR_AUTO, SPR_HERE, false, false, __VA_ARGS__)
```
Comment (jgabaut) [inline src/spuro.h:156]: I'm wondering how well does this interact with the zero-arg case the issue mentions.

Say, spr_logf(my_spr, "hey") versus spr_logf(my_spr, "%s", "hey")

Are they equivalent? Why the hell was I using ## in the first place then?

File: src/spuro.h [hunk 2]
```diff
@@ -196,59 +196,59 @@ void spr_logf_(const Spuro spr, SpuroLevel level, SpuroColor color, SpuroLoc loc
...
-#define spr_ttracef(format, ...) spr_tlogtf(SPR_DEFAULT, (format), ## __VA_ARGS__)
-#define spr_ctracef(color, format, ...) spr_clogtf(SPR_DEFAULT, (color), (format), ## __VA_ARGS__)
-#define spr_tctracef(color, format, ...) spr_tclogtf(SPR_DEFAULT, (color), SPR_HERE, (format), ## __VA_ARGS__)
-#define spr_ltracef(level, format, ...) spr_logtf_to(SPR_DEFAULT, (level), (format), ## __VA_ARGS__)
-#define spr_tltracef(level, format, ...) spr_tlogtf_to(SPR_DEFAULT, (level), (format), ## __VA_ARGS__)
-#define spr_cltracef(color, level, format, ...) spr_clogtf_to(SPR_DEFAULT, (color), (level), (format), ## __VA_ARGS__)
-#define spr_lctracef(level, color, format, ...) spr_clogtf_to(SPR_DEFAULT, (color), (level), (format), ## __VA_ARGS__)
-#define spr_tcltracef(color, level, format, ...) spr_tclogtf_to(SPR_DEFAULT, (color), (level), (color), (format), ## __VA_ARGS__)
-#define spr_tlctracef(level, color, format, ...) spr_tclogtf_to(SPR_DEFAULT, (color), (level), (color), (format), ## __VA_ARGS__)
+#define spr_tracef(...) spr_logtf(SPR_DEFAULT, __VA_ARGS__)
```
Comment (jgabaut) [inline src/spuro.h:242]: Maybe macros calling macros is a problem? You seem to have tested on both gcc and clang, well done.

I am a bit short on time for a few days, but if you leave things as-is, it's very likely this will get merged if it fixes the mentioned issue!

**Comment by jgabaut** [comment]
That's fine, I just copied my comments over! :)

Can you see them now? @khushal-banks

File: src/spuro.h (hunk 2 above)
Comment (ghost) [reply src/spuro.h:242]: I manually tested it with a custom `Makefile` on `linux`, this change removed the warning for both `gcc 13` and `clang 17`

I would request you to merge it only after testing on `windows` as well as on `macos`

File: src/spuro.h (hunk 1 above)
Comment (ghost) [reply src/spuro.h:156]: > Say, spr_logf(my_spr, "hey") versus spr_logf(my_spr, "%s", "hey")
> 
> Are they equivalent? Why the hell was I using ## in the first place then?

I believe you were using ## to remove the `,` after second parameter [same is suggested in this post](https://stackoverflow.com/questions/52891546/what-does-va-args-mean)

Accepted answer on the same post starts like, "It's a non-portable syntax introduced by gcc to specifically deal with this corner case of passing no arguments at all."

Other comments on the same post also suggests that it is not available with every compiler.

Issue #3 is also using a different compiler than gcc so that's why this is now an issue.

This PR includes changes which removes the requirement to use ##
- _spr_logf_ function always needs a format argument because of function syntax.

These change makes it possible to pass format in-place of ... and __VA_ARGS__ when no other arguments are supplied.

So, spr_logf(my_spr, "hey") and spr_logf(my_spr, "%s", "hey") both will translate to same thing.

```
spr_logf_(my_spr, SPR_NOLVL, SPR_COLOR_AUTO, SPR_HERE, false, false, "hey")
```

Without these changes, clang was seeing trailing comma because ## is supported by gcc and not clang

**Review by ghost — COMMENTED** [review]
It would be best if we can update [makefile.yml](https://github.com/jgabaut/spuro/blob/master/.github/workflows/makefile.yml) to windows and macos platform and more tests for different compilers.

File: src/spuro.h (hunk 2 above)
Comment (jgabaut) [reply src/spuro.h:242]: I'll make sure to give this a few spins before merging.

For now, it seems perfectly fine. I would ask you to please give me a few days to check the current state! :smile:

Thanks for the patience, this should get in (unless the unexpected happens).

File: src/spuro.h (hunk 1 above)
Comment (jgabaut) [reply src/spuro.h:156]: > I believe you were using ## to remove the `,` after second parameter [same is suggested in this post](https://stackoverflow.com/questions/52891546/what-does-va-args-mean)
> These change makes it possible to pass format in-place of ... and **VA_ARGS** when no other arguments are supplied.
> 
> So, spr_logf(my_spr, "hey") and spr_logf(my_spr, "%s", "hey") both will translate to same thing.
> Without these changes, clang was seeing trailing comma because ## is supported by gcc and not clang

So these changes don't have any drawback? The `##` was not needed?

I feel like I'm missing some problem that could arise. Maybe there's nothing.
Thanks for your patience.

File: src/spuro.h (hunk 2 above)
Comment (ghost) [reply src/spuro.h:242]: Thanks for considering this PR and finding time to review such small changes in your busy schedule.

**Comment by jgabaut** [comment]
I was thinking: [this commit](https://github.com/jgabaut/spuro/commit/3e0acfa007b7f64d9f0e37c150f1e6836c6428ae#diff-74535fd4b7adda73ad4d002ca7d9f70bb81eaf56d30427e6ad25cbfea27e516d) added a bunch of macro names to be called with no format (pass the plain cstring).

Would those be useless after this merge, if the changes solve the zero-arg conundrum?
Should the present names be refactored to point at new syntax?

**Comment by ghost** [comment]
> I was thinking: [this commit](https://github.com/jgabaut/spuro/commit/3e0acfa007b7f64d9f0e37c150f1e6836c6428ae#diff-74535fd4b7adda73ad4d002ca7d9f70bb81eaf56d30427e6ad25cbfea27e516d) added a bunch of macro names to be called with no format (pass the plain cstring).
> 
> Would those be useless after this merge, if the changes solve the zero-arg conundrum? Should the present names be refactored to point at new syntax?

I missed them. Yes to all of your questions.
In fact, i should have used new macros names with modified definition (changes in this PR)

Can i add a commit to reflect those changes in this PR?

**Comment by jgabaut** [comment]
> In fact, i should have used new macros names with modified definition (changes in this PR)
> 
> Can i add a commit to reflect those changes in this PR?

I'm not sure what you mean.

Could you explain what you mean before, or add these changes to a different branch (on top of this one) and link to it, so that the PR can stay as-is for now?

**Comment by ghost** [comment]
I will see what i can do.

**Comment by jgabaut** [comment]
I already tested on `Linux` and `mingw32` and it seems all good, I can only further test `macOS` later in the day.

**Comment by jgabaut** [comment]
> > In fact, i should have used new macros names with modified definition (changes in this PR)
> > Can i add a commit to reflect those changes in this PR?
> 
> I'm not sure what you mean.
> 
> Could you explain what you mean before, or add these changes to a different branch (on top of this one) and link to it, so that the PR can stay as-is for now?

Could you help me on this one? I'm trying to understand what you meant.

Do you mean something like still having a different name for functions forcing a format argument?

**Comment by ghost** [comment]
> or add these changes to a different branch (on top of this one) and link to it, so that the PR can stay as-is for now?

[Here](https://github.com/khushal-banks/spuro/compare/fixed_variadic_warnings...khushal-banks:spuro:refactoring) is the git diff of new branch.
[Here](https://github.com/khushal-banks/spuro/pull/1) is the PR of new changes on top of this PR. I don't know how to add you there for review.

I am not sure but I think you want some of these changes but i am not sure which ones.

**Comment by jgabaut** [comment]
> I am not sure but I think you want some of these changes but i am not sure which ones.

Thanks a lot, this is really close to what I was thinking.

I'm gonna reply here if you don't mind, but don't close that one yet.

The question I'm asking myself is: think of `printf()`.
It ends with a f, but it works with both explicit format and no format (plain cstring).
How does this relate to the mentioned clang warning? Is `printf()` using some kind of different trick to have correct behaviour for both cases, or is it just chalked up to the `va_` logic like we would do in this PR? (From my tests, this seems to work as expected).

If it's the latter (it just relies on `va_` functions like we would), then I think it's fine keeping the "f" in the names and just dropping the "string only" (no-format) macros would be the correct approach.

Still, I wonder if hiding this difference in the called macro would pose problems later. I guess as long as the underlying real signature has arguments before the variadic trail, we would be able to add new future parameters to the left part and old code could receive them by macro expansion with no problem.

Does keeping the explicit format argument in the macro signature allow for some selective logic that would not be possible otherwise? Any kind of validation being lost? I don't know.

Tested this PR and it seems to work as expected on `aarch64-Linux`, `x86_64-Linux`, `x86_64-w64-ming32`, `arm64-darwin`.

The real final question is, what advantages does the explicit format argument in macro definition allow?
I'm not sure if there are any.
Other than that, this seems a nice fix to the mentioned issue.

**Comment by ghost** [comment]
> The question I'm asking myself is: think of `printf()`.
> It ends with a f, but it works with both explicit format and no format (plain cstring).
> How does this relate to the mentioned clang warning? Is `printf()` using some kind of different trick to have correct behaviour for both cases,

Brother there is no trick.
Consider this,
```
// syntax for printf:
int printf(const char *restrict format, ...);

// syntax for our function:
void spr_logf_(const Spuro spr, SpuroLevel level, SpuroColor color, SpuroLoc loc, bool traced, bool timed, const char *format, ...);
```

They both are very similar. They both contain format argument. This clang issue is only with macros as explained below:

- If we use format argument is macro definition then `...` would have nothing so macro will end with a trailing `,`.
- On the other hand if we don't specify format argument in macro definition then `...` would at least have format argument so no trailing `,`

NOTE: syntax of spr_logf_ is not modified by PR.

> If it's the latter (it just relies on `va_` functions like we would), then I think it's fine keeping the "f" in the names and just dropping the "string only" (no-format) macros would be the correct approach.

I don't think keeping the "f" or removing it makes much difference. In my personal opinion, these macro would start making more sense if we remove "f" simply because `spr_log` is much more readable than `spr_logf`.

> Still, I wonder if hiding this difference in the called macro would pose problems later. I guess as long as the underlying real signature has arguments before the variadic trail, we would be able to add new future parameters to the left part and old code could receive them by macro expansion with no problem.
> 
> Does keeping the explicit format argument in the macro signature allow for some selective logic that would not be possible otherwise? Any kind of validation being lost? I don't know.

For now, i don't see any issue. But i would say i am no expert. I happen to know solution for #3 so i tried my best to fix it. In my understanding compiler will first replace all macros with their expansion at pre-processing stage so this PR should pose no problem. Actually, it is only valid solution to solve #3 unless clang starts supporting `##`


> Tested this PR and it seems to work as expected on `aarch64-Linux`, `x86_64-Linux`, `x86_64-w64-ming32`, `arm64-darwin`.
>
> The real final question is, what advantages does the explicit format argument in macro definition allow? I'm not sure if there are any. Other than that, this seems a nice fix to the mentioned issue.

I was wondering that there could be some unknown arch-specific implementation that could break this PR. If this works, please merge it. Because it won't be wrong. It should be acceptable to deal with unknown issues later.

For your final question. I would start my answer by saying feel free to ask more questions. I believe you are forgetting that macros are only text replacement. We are removing format argument from macro definition so it could take place of `...` when no other arguments are specified.

**Comment by ghost** [comment]
I would request you to merge this PR.
Refactoring should be handled by a separate issue which would list:
- names of macros that should contain f
- names of macros that should not contain f
- names of macros that should be removed
- other changes (if necessary)

If you don't think this PR can be merged. I would happily close this.
